FROM sitkoru/php7:dev

RUN apt update \
    && apt install -y $PHPIZE_DEPS openssh-server git unzip rsync \
    && pecl install xdebug ast \
    && docker-php-ext-enable ast \
    && apt purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $PHPIZE_DEPS \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY config/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin -- --filename=composer

RUN composer global require "fxp/composer-asset-plugin:^1.4.2" --prefer-dist
RUN composer global require "hirak/prestissimo:^0.3" --prefer-dist


