FROM hub.0xdev.ru/servers/docker-php7

RUN apt update \
    && apt install -y $PHPIZE_DEPS openssh-server git \
    && pecl install xdebug \
    && apt purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false $PHPIZE_DEPS \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini